theme: jekyll-theme-minimal
title: "Thomas Trigo Trindade's website"
description: "Thomas Trigo Trindade — postdoctoral researcher in computational applied mathematics at KAUST."
logo: /assets/img/logo.jpg

url: "https://trigotri.github.io"

plugins:
  - jekyll-sitemap

header_pages:
  - index.md
  - about.md
  - publications.md
  - news.md
