remote_theme: "jekyll/minima"
title: "Thomas Trigo Trindade's website"
description: "Where you can keep up-to-date with what I've been up to."

header_pages:
  - index.md
  - about.md
  - publications.md
  - news.md
